/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FileOptionsPanel.java
 *
 * Created on Sep 19, 2011, 5:09:02 PM
 */
package evetycoon;

import java.io.File;
import java.io.IOException;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import services.EnumFileProperties;

/**
 *
 * @author hrivanov
 */
public class FileOptionsPanel extends javax.swing.JPanel implements OptionPanelInterface
{

  private Properties fileProperties;
  private JFileChooser dirChooser;

  /** Creates new form FileOptionsPanel */
  public FileOptionsPanel()
  {
    initComponents();

    dirChooser = new JFileChooser();
    dirChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

    this.fileProperties = new Properties();

    for (EnumFileProperties propertyName : EnumFileProperties.values())
    {
      this.fileProperties.setProperty(propertyName.propertyName(), propertyName.defaultValue());
    }
  }

  public Properties getProperties()
  {
    this.fileProperties.setProperty(EnumFileProperties.GENERAL_PATH.propertyName(), genDirPathField.getText());
    this.fileProperties.setProperty(EnumFileProperties.IMAGE_CACHE_PATH.propertyName(), imgCacheDirField.getText().toString());

    return fileProperties;
  }

  public void setProperties(Properties fileProperties)
  {
    try
    {
      String propertyName;
      String foundValue;
      File currentDirPath = new File(".");
      String currentDir = currentDirPath.getCanonicalPath();

      propertyName = EnumFileProperties.GENERAL_PATH.propertyName();
      foundValue = fileProperties.getProperty(propertyName, currentDir);
      this.fileProperties.setProperty(propertyName, foundValue);
      genDirPathField.setText(currentDir + foundValue);

      propertyName = EnumFileProperties.IMAGE_CACHE_PATH.propertyName();
      foundValue = fileProperties.getProperty(propertyName, "images");
      this.fileProperties.setProperty(propertyName, foundValue);
      imgCacheDirField.setText(currentDir + "\\" + foundValue);

      this.fileProperties = fileProperties;
    } catch (IOException ex)
    {
      Logger.getLogger(FileOptionsPanel.class.getName()).log(Level.SEVERE, null, ex);
    }
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    genDirPathPanel = new javax.swing.JPanel();
    genDirPathField = new javax.swing.JTextField();
    genDirPathBtn = new javax.swing.JButton();
    genDirPathLabel = new javax.swing.JLabel();
    imgCacheDirPanel = new javax.swing.JPanel();
    imgCacheDirField = new javax.swing.JTextField();
    imgCacheDirBtn = new javax.swing.JButton();
    imgCacheDirLabel = new javax.swing.JLabel();

    setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
    setName("Form"); // NOI18N
    setPreferredSize(new java.awt.Dimension(350, 160));

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(evetycoon.EveTycoonApp.class).getContext().getResourceMap(FileOptionsPanel.class);
    genDirPathPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("genDirPathPanel.border.title"))); // NOI18N
    genDirPathPanel.setName("genDirPathPanel"); // NOI18N

    genDirPathField.setText(resourceMap.getString("genDirPathField.text")); // NOI18N
    genDirPathField.setName("genDirPathField"); // NOI18N

    genDirPathBtn.setText(resourceMap.getString("genDirPathBtn.text")); // NOI18N
    genDirPathBtn.setName("genDirPathBtn"); // NOI18N
    genDirPathBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        genDirPathBtnActionPerformed(evt);
      }
    });

    genDirPathLabel.setText(resourceMap.getString("genDirPathLabel.text")); // NOI18N
    genDirPathLabel.setName("genDirPathLabel"); // NOI18N

    javax.swing.GroupLayout genDirPathPanelLayout = new javax.swing.GroupLayout(genDirPathPanel);
    genDirPathPanel.setLayout(genDirPathPanelLayout);
    genDirPathPanelLayout.setHorizontalGroup(
      genDirPathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, genDirPathPanelLayout.createSequentialGroup()
        .addComponent(genDirPathLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(genDirPathField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(genDirPathBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    genDirPathPanelLayout.setVerticalGroup(
      genDirPathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(genDirPathPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(genDirPathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(genDirPathField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(genDirPathBtn)
          .addComponent(genDirPathLabel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    imgCacheDirPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), resourceMap.getString("imgCacheDirPanel.border.title"))); // NOI18N
    imgCacheDirPanel.setName("imgCacheDirPanel"); // NOI18N

    imgCacheDirField.setName("imgCacheDirField"); // NOI18N

    imgCacheDirBtn.setText(resourceMap.getString("imgCacheDirBtn.text")); // NOI18N
    imgCacheDirBtn.setName("imgCacheDirBtn"); // NOI18N
    imgCacheDirBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        imgCacheDirBtnActionPerformed(evt);
      }
    });

    imgCacheDirLabel.setText(resourceMap.getString("imgCacheDirLabel.text")); // NOI18N
    imgCacheDirLabel.setName("imgCacheDirLabel"); // NOI18N

    javax.swing.GroupLayout imgCacheDirPanelLayout = new javax.swing.GroupLayout(imgCacheDirPanel);
    imgCacheDirPanel.setLayout(imgCacheDirPanelLayout);
    imgCacheDirPanelLayout.setHorizontalGroup(
      imgCacheDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imgCacheDirPanelLayout.createSequentialGroup()
        .addComponent(imgCacheDirLabel)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(imgCacheDirField, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(imgCacheDirBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap())
    );
    imgCacheDirPanelLayout.setVerticalGroup(
      imgCacheDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(imgCacheDirPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addGroup(imgCacheDirPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(imgCacheDirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(imgCacheDirBtn)
          .addComponent(imgCacheDirLabel))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
    this.setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(genDirPathPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addComponent(imgCacheDirPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(genDirPathPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(imgCacheDirPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
  }// </editor-fold>//GEN-END:initComponents

  private void genDirPathBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_genDirPathBtnActionPerformed
  {//GEN-HEADEREND:event_genDirPathBtnActionPerformed
    int returnVal = dirChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION)
    {
      File file = dirChooser.getSelectedFile();
      //This is where a real application would open the file.
      genDirPathField.setText(file.getAbsolutePath());
    } 
  }//GEN-LAST:event_genDirPathBtnActionPerformed

  private void imgCacheDirBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_imgCacheDirBtnActionPerformed
  {//GEN-HEADEREND:event_imgCacheDirBtnActionPerformed
    
    int returnVal = dirChooser.showOpenDialog(this);
    if (returnVal == JFileChooser.APPROVE_OPTION)
    {
      File file = dirChooser.getSelectedFile();
      //This is where a real application would open the file.
      imgCacheDirField.setText(file.getAbsolutePath());
    } 
  }//GEN-LAST:event_imgCacheDirBtnActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton genDirPathBtn;
  private javax.swing.JTextField genDirPathField;
  private javax.swing.JLabel genDirPathLabel;
  private javax.swing.JPanel genDirPathPanel;
  private javax.swing.JButton imgCacheDirBtn;
  private javax.swing.JTextField imgCacheDirField;
  private javax.swing.JLabel imgCacheDirLabel;
  private javax.swing.JPanel imgCacheDirPanel;
  // End of variables declaration//GEN-END:variables
}
