/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * OptionsDialog.java
 *
 * Created on Sep 19, 2011, 3:38:22 PM
 */
package evetycoon;

import java.util.Enumeration;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author hrivanov
 */
public class OptionsDialog extends javax.swing.JDialog
{
  private Properties appProperties;

  /** Creates new form OptionsDialog */
  public OptionsDialog(java.awt.Frame parent, boolean modal)
  {
    super(parent, modal);
    initComponents();
    
    this.setLocationRelativeTo(parent);
    
    appProperties = new Properties();  
  }
  
  public Properties getProperties()
  {
    return appProperties;
  }
  
  public void setProperties(Properties newProperties)
  {  
    appProperties = newProperties;
    
    this.generalOptPanel.setProperties(appProperties);
    this.networkOptPanel.setProperties(appProperties);
    this.fileOptPanel.setProperties(appProperties);
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    optionsTabbedPane = new javax.swing.JTabbedPane();
    generalOptPanel = new evetycoon.GeneralOptionsPanel();
    noOptLabel = new javax.swing.JLabel();
    networkOptPanel = new evetycoon.NetworkOptionsPanel();
    fileOptPanel = new evetycoon.FileOptionsPanel();
    okBtn = new javax.swing.JButton();
    cancelBtn = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(evetycoon.EveTycoonApp.class).getContext().getResourceMap(OptionsDialog.class);
    setTitle(resourceMap.getString("appOptionsForm.title")); // NOI18N
    setModalityType(java.awt.Dialog.ModalityType.APPLICATION_MODAL);
    setName("appOptionsForm"); // NOI18N

    optionsTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
    optionsTabbedPane.setName("optionsTabbedPane"); // NOI18N

    generalOptPanel.setName("generalOptPanel"); // NOI18N

    noOptLabel.setText(resourceMap.getString("noOptLabel.text")); // NOI18N
    noOptLabel.setName("noOptLabel"); // NOI18N

    javax.swing.GroupLayout generalOptPanelLayout = new javax.swing.GroupLayout(generalOptPanel);
    generalOptPanel.setLayout(generalOptPanelLayout);
    generalOptPanelLayout.setHorizontalGroup(
      generalOptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(generalOptPanelLayout.createSequentialGroup()
        .addGap(152, 152, 152)
        .addComponent(noOptLabel)
        .addContainerGap(158, Short.MAX_VALUE))
    );
    generalOptPanelLayout.setVerticalGroup(
      generalOptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(generalOptPanelLayout.createSequentialGroup()
        .addGap(83, 83, 83)
        .addComponent(noOptLabel)
        .addContainerGap(86, Short.MAX_VALUE))
    );

    optionsTabbedPane.addTab(resourceMap.getString("generalOptPanel.TabConstraints.tabTitle"), generalOptPanel); // NOI18N

    networkOptPanel.setName("networkOptPanel"); // NOI18N
    optionsTabbedPane.addTab(resourceMap.getString("networkOptPanel.TabConstraints.tabTitle"), networkOptPanel); // NOI18N

    fileOptPanel.setName("fileOptPanel"); // NOI18N
    optionsTabbedPane.addTab(resourceMap.getString("fileOptPanel.TabConstraints.tabTitle"), fileOptPanel); // NOI18N

    okBtn.setText(resourceMap.getString("okBtn.text")); // NOI18N
    okBtn.setName("okBtn"); // NOI18N
    okBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        okBtnActionPerformed(evt);
      }
    });

    cancelBtn.setText(resourceMap.getString("cancelBtn.text")); // NOI18N
    cancelBtn.setName("cancelBtn"); // NOI18N
    cancelBtn.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        cancelBtnActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(342, Short.MAX_VALUE)
        .addComponent(cancelBtn)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(okBtn))
      .addComponent(optionsTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
    );

    layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelBtn, okBtn});

    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(optionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 192, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(okBtn)
          .addComponent(cancelBtn))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void okBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_okBtnActionPerformed
  {//GEN-HEADEREND:event_okBtnActionPerformed
    Enumeration propEnumeration;
    String key;
    Properties currProperties;
    
    try
    {
      currProperties = generalOptPanel.getProperties();
      propEnumeration = currProperties.propertyNames();
      while(propEnumeration.hasMoreElements())
      {
        key = (String)propEnumeration.nextElement();
        appProperties.setProperty(key, currProperties.getProperty(key));
      }

      currProperties = networkOptPanel.getProperties();
      propEnumeration = currProperties.propertyNames();
      while(propEnumeration.hasMoreElements())
      {
        key = (String)propEnumeration.nextElement();
        appProperties.setProperty(key, currProperties.getProperty(key));
      }

      currProperties = fileOptPanel.getProperties();
      propEnumeration = currProperties.propertyNames();
      while(propEnumeration.hasMoreElements())
      {
        key = (String)propEnumeration.nextElement();
        appProperties.setProperty(key, currProperties.getProperty(key));
      }

      // Do anything neede with the new properties.
      EveTycoonApp.getApplication().setAppProxy();
      EveTycoonApp.getApplication().saveAppProperties();
              
      this.setVisible(false);
    }
    catch(Exception genEx)
    {
      JOptionPane.showMessageDialog(this,
                genEx.getMessage(),
                "Exception",
                JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_okBtnActionPerformed

  private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cancelBtnActionPerformed
  {//GEN-HEADEREND:event_cancelBtnActionPerformed
    this.setVisible(false);
  }//GEN-LAST:event_cancelBtnActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[])
  {
    java.awt.EventQueue.invokeLater(new Runnable()
    {

      public void run()
      {
        OptionsDialog dialog = new OptionsDialog(new javax.swing.JFrame(), true);
        dialog.addWindowListener(new java.awt.event.WindowAdapter()
        {

          @Override
          public void windowClosing(java.awt.event.WindowEvent e)
          {
            System.exit(0);
          }
        });
        dialog.setVisible(true);
      }
    });
  }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton cancelBtn;
  private evetycoon.FileOptionsPanel fileOptPanel;
  private evetycoon.GeneralOptionsPanel generalOptPanel;
  private evetycoon.NetworkOptionsPanel networkOptPanel;
  private javax.swing.JLabel noOptLabel;
  private javax.swing.JButton okBtn;
  private javax.swing.JTabbedPane optionsTabbedPane;
  // End of variables declaration//GEN-END:variables
}
